settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: codetest
  path: .
  commands:
    install:
      status: true
      method: go build -o codetest
    run:
      status: true
      method: ./codetest
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
